---


- hosts: all
  become: true
  
  tasks:
  - name: Stopping the nginx
    service:
      name: nginx
      state: stopped

  - name: Removing the nginx package
    yum:
      name: nginx
      state: absent


